repos:
  - repo:  https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: ["ProjectsWebsite", "--target-version", "py310"]
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--src", "ProjectsWebsite", "--profile", "black", "--gitignore"]
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: check-docstring-first
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.1.0
    hooks:
      - id: pycln
        args: [--config=pycln-config.yaml]
        language_version: python3