"""empty message

Revision ID: 14e591430b99
Revises: 
Create Date: 2021-07-17 10:33:03.628886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e591430b99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_articles():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('download_pdf', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade_articles():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'download_pdf')
    # ### end Alembic commands ###


def upgrade_blacklist():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_blacklist():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

