"""empty message

Revision ID: f2ffb2f480e6
Revises: Initialization: Added tanles: 'article' and 'blacklist
Create Date: 2021-11-09 17:54:40.218533

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f2ffb2f480e6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("create_date", sa.String(length=100), nullable=True),
        sa.Column("short_description", sa.String(), nullable=True),
        sa.Column("title_img", sa.String(), nullable=True),
        sa.Column("body", sa.String(), nullable=True),
        sa.Column("download_pdf", sa.LargeBinary(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "blacklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("person", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column("date", sa.String(length=30), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("person"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blacklist")
    op.drop_table("article")
    # ### end Alembic commands ###
